# Generated by Django 3.2.9 on 2021-11-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datajual',
            name='jumlah',
            field=models.IntegerField(max_length=100),
        ),
    ]
