# Generated by Django 3.2.9 on 2021-11-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jual', '0002_alter_datajual_jumlah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datajual',
            name='harga',
            field=models.IntegerField(max_length=100),
        ),
    ]
