# Generated by Django 3.2.9 on 2021-11-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataJeans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idjeans', models.CharField(max_length=100)),
                ('merk', models.CharField(max_length=100)),
                ('ukuran', models.CharField(max_length=100, null=True)),
                ('stok', models.CharField(max_length=100)),
                ('harga', models.CharField(max_length=100)),
                ('keterangan', models.CharField(max_length=100, null=True)),
                ('tanggal', models.DateField(null=True)),
            ],
        ),
    ]
