# Generated by Django 3.2.9 on 2021-11-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datajeans',
            name='stok',
            field=models.IntegerField(max_length=100),
        ),
    ]
